### ISSUE TITLE
divide-* bug

### ISSUE THREAD

**Issue by flyingmachine** [green-coder/girouette#84]
I'm running into an issue when using girouette via https://github.com/lambdaisland/ornament. Apologies if I should be reporting this in that project instead of this one

Given the following:

```clojure
(ns donut.todo-example.frontend.components.todo-list.list)

(o/defstyled ul :div
  :max-w-7xl :mx-auto :sm:px-6 :lg:-px-8
  [:>.list-container :bg-white :shadow :overflow-hidden :sm:rounded-md]
  [:>.list-container>ul :divide-y :divide-gray-200]
  [:>.list-container>ul>li :p-3]
  ([& list-items]
   [:<>
    (into
     [:div.list-container
      (into
       [:ul {:role "list"}]
       list-items)])]))

(defn component
  []
  [:div "my list"
   [ui/ul
    [:li "list item 1"]
    [:li "list item 2"]
    [:li "list item 3"]
    [:li "list item 4"]
    [:li "list item 5"]]])
```

This css gets produced:

```css
.donut_todo-example_frontend_components_todo-list_list__ul>.list-container>ul>*+* {
    border-top-width: calc(1px * var(--gi-divide-y-reverse));
    border-bottom-width: calc(1px * calc(1 - var(--gi-divide-y-reverse)));
}
```

This rule references the var `--gi-divide-y-reverse`, but that var isn't generated.

Additionally, these rules look different from those generated by tailwind:

```css
.divide-y > :not([hidden]) ~ :not([hidden]) {
    --tw-divide-y-reverse: 0;
    border-top-width: calc(1px * calc(1 - var(--tw-divide-y-reverse)));
    border-bottom-width: calc(1px * var(--tw-divide-y-reverse));
}
```

I guess they're functionally the same, but thought I'd share anyway :)

Thanks for this cool library!
